###

GET http://localhost:4600/seebouquets


###

POST http://localhost:4600/addbouquet
Content-Type: application/json

{
    "image": "frekgbnregjrbegker",
    "title": "New Bouquet 2",
    "description": "Some description for this bouquet 2",
    "price": 40,
    "stock": 1
}

###

PUT http://localhost:4600/updatebouqprice
Content-Type: application/json

{
    "title": "fkwebfekjwf",
    "description": "fksfbek",
    "price": 100,
    "stock": 1,
    "image": "fkjrbfhjrekf"
    
}

###

DELETE http://localhost:4600/deletebouquet
Content-Type: application/json

{
    "id": 4
}





# ETIQUETTE


###

GET http://localhost:4600/bouquets


###

POST http://localhost:4600/bouquets
Content-Type: application/json

{
    "image": "frekgbnregjrbegker",
    "title": "New Bouquet 23",
    "description": "Some description for this bouquet 23",
    "price": 230,
    "stock": 0
}


# TEST THIS!

###

PUT http://localhost:4600/bouquets/10
Content-Type: application/json

{
    "title": "fkwebfekjwf",
    "description": "fksfbek",
    "price": 100,
    "stock": 1,
    "image": "fkjrbfhjrekf"
    
}

###

PUT http://localhost:4600/updatestock/11
Content-Type: application/json

{
    "stock": 0
}

###

DELETE http://localhost:4600/bouquets/6





###

DELETE http://localhost:4600/bouquets/17

###

GET http://localhost:4600/bouquets/





###

GET http://localhost:4600/bouquets/1
Content-Type: application/json

{
    "id": "tom cruise"
}

# Tests req.params.id in node console


###

GET http://localhost:4600/bouquets/1
# Content-Type: application/json

# {
#     "id": "tom cruise"
# }

# Tests req.params.id in node console


###
POST http://localhost:4600/validateuser
Content-Type: application/json

{
    "email": "a@aa.com",
    "password": 54321
}

